// <auto-generated />
namespace PumaCoinCatalog.Data
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addBullionValueToCoinType : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addBullionValueToCoinType));
        
        string IMigrationMetadata.Id
        {
            get { return "201802240014199_addBullionValueToCoinType"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
