// <auto-generated />
namespace PumaCoinCatalog.Data
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class storedProcGetChecklistValueSummary_funcCalculateCbChecklistValue : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(storedProcGetChecklistValueSummary_funcCalculateCbChecklistValue));
        
        string IMigrationMetadata.Id
        {
            get { return "201805240348359_storedProcGetChecklistValueSummary_funcCalculateCbChecklistValue"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
